fraud:
  outputs:
    dev:
      account: UFQWVTI-VL57671
      database: FRAUD_DETECTION
      password: Loans_pwd_2025
      role: AIRBYTE_ROLE
      schema: prod
      threads: 1
      type: snowflake
      user: AIRBYTE_USER
      warehouse: AIRBYTE_WAREHOUSE
  target: dev
